export const GET_ERRORS = "GET ERRORS";
export const GET_PROJECTS = "GET_PROJECTS";
export const GET_PROJECT_BY_ID = "GET_PROJECT_BY_ID";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const DELETE_PROJECT = "DELETE_PROJECT";
